### ISSUE TITLE
React Nginx Docker container exits with SIGINT3 error code

### ISSUE THREAD

**Issue by julian-patterson** [canadrian72/led-control-center#6]
Good resource:
* [Article with possible causes](https://vsupalov.com/docker-compose-stop-slow/)

**Comment by adrian-patterson** [comment]
@julian-patterson oh stop whining will you? It works doesn't it?

**Comment by julian-patterson** [comment]
No, stopped working this morning.

**Comment by adrian-patterson** [comment]
Oof. I'll take a look at the logs when I get home
